spring:
  main:
    banner-mode: "off"
    
logging:
  level:
    org.philbour: DEBUG

server:
  servlet:
    context-path: /balance
    
springdoc:
  swagger-ui.path: /docs/swagger-ui
  api-docs.path: /docs